package com.deepfakedetector.exception;

import lombok.Getter;

@Getter
public enum DetectionErrorCode implements Classifiable {

    // Success
    SUCCESS_MESSAGE_AR("SUCCESS_MESSAGE_AR"),
    SUCCESS_MESSAGE_EN("SUCCESS_MESSAGE_EN"),
    NO_USER_FOR_ACTIVATION_KEY("NO_USER_FOR_ACTIVATION_KEY"),
    NO_USER_FOR_RESET_KEY("NO_USER_FOR_RESET_KEY"),
    INVALID_INPUT("INVALID_INPUT"),
    // General
    INVALID_SORT_PROPERTY("INVALID_SORT_PROPERTY"),
    GENERAL_ERROR("GENERAL_ERROR"),
    DETECTION_FAILED("DETECTION_FAILED"),
    FILE_ALREADY_EXISTS("FILE_ALREADY_EXISTS"),
    FILE_NOT_FOUND("FILE_NOT_FOUND"),
    USER_NOT_FOUND("USER_NOT_FOUND"),
    NO_FACE_DETECTED("NO_FACE_DETECTED"),

    // Video errors
    VIDEO_TOO_LONG("VIDEO_TOO_LONG"),
    VIDEO_FILE_TOO_LARGE("VIDEO_FILE_TOO_LARGE"),
    VIDEO_NOT_FOUND("VIDEO_NOT_FOUND"),
    UNABLE_TO_DETERMINE_DURATION("UNABLE_TO_DETERMINE_DURATION"),
    FAILED_TO_EXTRACT_DURATION("FAILED_TO_EXTRACT_DURATION"),
    FAILED_TO_ANALYZE_VIDEO("FAILED_TO_ANALYZE_VIDEO"),
    INVALID_OR_CORRUPTED_VIDEO("INVALID_OR_CORRUPTED_VIDEO"),

    // Profile image errors
    EMPTY_OR_MISSING_FILE("EMPTY_OR_MISSING_FILE"),
    IMAGE_FILE_TOO_LARGE("IMAGE_FILE_TOO_LARGE"),
    PROFILE_IMAGE_NOT_FOUND("PROFILE_IMAGE_NOT_FOUND"),

    // Authentication & user errors
    USERNAME_ALREADY_USED("USERNAME_ALREADY_USED"),
    EMAIL_ALREADY_USED("EMAIL_ALREADY_USED"),
    INVALID_PASSWORD("INVALID_PASSWORD"),
    INVALID_RESET_KEY("INVALID_RESET_KEY"),
    CURRENT_USER_NOT_FOUND("CURRENT_USER_NOT_FOUND"),
    ACTIVATION_KEY_NOT_FOUND("ACTIVATION_KEY_NOT_FOUND"),
    RESET_KEY_NOT_FOUND("RESET_KEY_NOT_FOUND"),
    ACCESS_DENIED("ACCESS_DENIED"),
    AUTHENTICATION_FAILED("AUTHENTICATION_FAILED"),
    // File service errors
    FILE_COPY_ERROR("FILE_COPY_ERROR"),
    FILE_FORMAT_NOT_SUPPORTED("FILE_FORMAT_NOT_SUPPORTED");

    private final String label;

    DetectionErrorCode(final String label) {
        this.label = label;
    }

    @Override
    public String getClassName() {
        return this.label;
    }
}